---
- name: takes up a development environment
  hosts: all
  become: True

  vars:
    tomcat_version9: 9.0.14
    tomcat_version: 9
    wars:
      - url: file:///vagrant/springykotlin.war

  tasks:
    - name: Start service tomcat, if not started
      service:
        name: tomcat
        state: started

  roles:
    - robertdebock.java
    - robertdebock.tomcat
